language: ruby
before_script:
  - export RUBYOPT="--enable-frozen-string-literal"

script: rake spec:travis
before_script:
  - travis_retry rake -E 'module ::Bundler; VERSION = "0.0.0"; end' override_version
  - travis_retry rake spec:travis:deps
  - travis_retry rake man:build
  - travis_retry rake spec:rubygems:clone_rubygems_$RGV

rvm:
  - 2.5.2
  - 2.4.5
  - 2.3.8

# Rubygems versions MUST be available as rake tasks
# see Rakefile:125 for the list of possible RGV values
env:
  # We need to know if changes to rubygems will break bundler on release
  - RGV=master
  # Test the latest rubygems release with all of our supported rubies
  - RGV=v2.7.7

matrix:
  include:
    # Ruby 2.4, Rubygems 2.6 and up
    - rvm: 2.4.2
      env: RGV=v2.6.14
    # Ruby 2.3, Rubygems 2.5 and up
    - rvm: 2.3.7
      env: RGV=v2.5.2
    - rvm: 2.3.7
      env: RGV=v2.6.14
    # Ruby-head (we want to know how we're doing, but not fail the build)
    - rvm: ruby-head
      env: RGV=master
    # 1.x mode (we want to keep stuff passing in 1.x mode for now)
    - rvm: 2.5.1
      env: RGV=v2.7.7 BUNDLER_SPEC_SUB_VERSION=1.98
    - rvm: 1.8.7
      env: RGV=v2.7.7 BUNDLER_SPEC_SUB_VERSION=1.98

  allow_failures:
    - rvm: ruby-head
      env: RGV=master
